steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy frontend_bc/app.yaml --quiet --promote',
      ]

timeout: '1600s'

options:
  logging: CLOUD_LOGGING_ONLY
